### ISSUE TITLE
Improve API documentation 

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-server#3]
We have begun documenting it using [jsdoc](https://jsdoc.app/). 

We'd like to expand and improve upon what has been made. 

Please, comment below if you have any further questions regarding how any problem was approached!

**Comment by mlimos** [comment]
hi, I'd like to help out with this if nobody else has picked it up. Are you set on using jsdoc, or would you open to other documentation tools like swagger?

**Comment by viniciusarre** [comment]
HI @mlimos 
Thank you for your interest in this project! 
I personally don't have any objection to using other tools! Just keep in mind you'll need to rewrite the documentation created in jsdoc with swagger (which isn't a lot). So, I'd say, go ahead! 
I look forward to reviewing your contributions!
