### ISSUE TITLE
Add API testing

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-server#4]
I have been considering using [jest](https://jestjs.io/) for such. 

Suggestions are welcome!

**Comment by cainwatson** [comment]
@viniciusarre I can get working on this. What version of node have you been using?

**Comment by viniciusarre** [comment]
Hi @cainwatson, thank you for your interest in this repository!
I've run the project using v10.16.3.
I've recently updated the dependencies, so I think there won't be a problem running it in newer versions!

**Comment by viniciusarre** [comment]
Further testing will be added further, closing this for now!
