### ISSUE TITLE
Add authentication token (JWT)

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-server#5]

**Comment by Nerocodes** [comment]
Can I be assigned to this? Also, this means generating a token on login and signup but does it also include a middleware to verify the token?

**Comment by viniciusarre** [comment]
Hi, @Nerocodes 
Thank you for your interest in contributing to this project!
I've been thinking about creating the token when the user creates the account and saving it to db (I thought about a token per user, but I suppose we could add an expiration date for the token and make the user recreate it upon login in the future...). 
But, for now, I think we can approach a simpler flow, such as, the user signs up, we generate and store the token in the user's model and require it, validating whether the user is authenticated in the controller (I usually create a new helper function in auth helpers for the whole flow)...

This would, therefore include the functions for validating the token and signup. 

If you'd like to work on this issue, please, create a new branch and mention it! I believe that this way we'll have some feedback on the issue that you have been working on it!

I look forward to reviewing your contributions! Let me know if you have any further questions!
