### ISSUE TITLE
Refactor Quotes model fields to English

### ISSUE THREAD

**Issue by viniciusarre** [viniciusarre/quote-a-lang-server#8]
When I started programming this, I have created its Quote models in Portuguese. It needs refactoring to reflect the keys in their English equivalents, which takes some throughout refactoring... For example, the following model

```
const mongoose = require("mongoose");

const fraseSchema = new mongoose.Schema({
  _id: { type: Number },
  idioma: { type: String, default: "fr" },
  autor: { type: String },
  bandeira: { type: String },
  nome_url: { type: String },
  dados: { type: Array }
});

fraseSchema.pre("save", next => {
  next();
});

module.exports = mongoose.model("frase", fraseSchema);

```

should be refactored to...

```

const mongoose = require("mongoose");

const quoteSchema = new mongoose.Schema({
  _id: { type: Number },
  language: { type: String, default: "fr" },
  author: { type: String },
  flag: { type: String },
  name_url: { type: String },
  data: { type: Array }
});

quoteSchema.pre("save", next => {
  next();
});

module.exports = mongoose.model("quote", quoteSchema);
```

Please, keep in mind that there is a lot of reference to this model in the code, be careful!

Bonus points if you manage to fix the tests as well!

**Comment by spassarop** [comment]
I can do this for you

**Comment by viniciusarre** [comment]
Hi @spassarop! Thank you for your interest in this repository! I'd love to review your PR soon! Let me know if you have any questions!
